name: Github-Gitlab-Sync

on:
  push:
    branches:
       - '*'
  
  delete:
      branches:
         - '*'

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Gitlab sync
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TARGET_TOKEN }}

      run: |
        git remote add https://oauth2:${{ secrets.GITLAB_TARGET_TOKEN }}@gitlab.hrz.tu-chemnitz.de/vsr/edu/planspiel/ws2425/group11-techblend.git
        git push gitlab --all
        git push gitlab --tags
  
